name: digital_detox_coach
description: DIGITAL DETOX COACH - voluntary focus and wellbeing coach.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
